sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libxss-dev
    - build-essential
    - automake
    - autoconf
    - autopoint
    - libtool
    - gettext
    - pkg-config
    - help2man
    - texinfo

script:
  - ./bootstrap
  - ./configure
  - make
  - make test
