language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - \# Installing libraries
  - sudo apt-get install -qq libxss-dev
  - \# Installing build tools
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq automake autoconf libtool gettext
  - sudo apt-get install -qq pkg-config

script:
  - ./bootstrap
  - ./configure
  - make
  - make test
