sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libxss-dev
    - build-essential
    - automake
    - autoconf
    - autopoint
    - libtool
    - gettext
    - pkg-config
    - help2man
    - texinfo
    - gnulib

script:
  - ./bootstrap --no-git --gnulib-srcdir=/usr/share/gnulib
  - ./configure
  - make
  - make check
  - make install
